
##################################################################################################################
#    ██╗     ██╗   ██╗███╗   ██╗ █████╗ ██████╗     ███████╗██████╗ ███████╗███████╗ ██████╗ █████╗ ███╗   ███╗  #
#    ██║     ██║   ██║████╗  ██║██╔══██╗██╔══██╗    ██╔════╝██╔══██╗██╔════╝██╔════╝██╔════╝██╔══██╗████╗ ████║  #
#    ██║     ██║   ██║██╔██╗ ██║███████║██████╔╝    █████╗  ██████╔╝█████╗  █████╗  ██║     ███████║██╔████╔██║  #
#    ██║     ██║   ██║██║╚██╗██║██╔══██║██╔══██╗    ██╔══╝  ██╔══██╗██╔══╝  ██╔══╝  ██║     ██╔══██║██║╚██╔╝██║  #
#    ███████╗╚██████╔╝██║ ╚████║██║  ██║██║  ██║    ██║     ██║  ██║███████╗███████╗╚██████╗██║  ██║██║ ╚═╝ ██║  #
#    ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝    ╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝  #
#                                          Made By Magas8                                                        #
##################################################################################################################




##################################################
#                   Messages                     #
##################################################
freecam-mode-on-success: '&8&l[&2&l!&8&l] &7Successfully went into FreeCam mode.'
freecam-mode-off-success: '&8&l[&2&l!&8&l] &7Successfully went back to your previous location.'
too-many-arguments-message: '&8&l[&c&l!&8&l] &7Too many arguments. Usage: &5/freecam'
cannot-use-commands-message: '&8&l[&c&l!&8&l] &7You cant use commands while in FreeCam mode.'
maximum-distance-reached-message: '&8&l[&c&l!&8&l] &7You have reached the maximum allowed distance.'
no-permission-message: '&8&l[&c&l!&8&l] &7You dont have permission to use this command.'
freecam-cooldown: "&8&l[&c&l!&8&l] &7You must wait %seconds% seconds before you do it again."
freecam-spectate-teleport: "&8&l[&c&l!&8&l] &7You cant teleport when you are at freecam mode."
freecam-action-bar: "&8&l[&b&lFreeCam&8&l] &c&l%seconds% &8seconds left."
freecam-canceled: "&8&l[&c&l!&8&l] &cYour freecam canceled"
freecam-max-distance-reach: "&8&l[&c&l!&8&l] &7You have reached the max distance of Blocks"
freecam-reload: "&8&l[&c&l!&8&l] &7Config reloaded Successfully"
freecam-no-use: "&8&l[&c&l!&8&l] &7You are not in freecam mode"
freecam-money-charge: "&8&l[&2&l!&8&l] &7You have been charged &a%money%"
freecam-no-money: "&8&l[&c&l!&8&l] &7Insufficient balance"
on-freecam-cmd: "&8&l[&c&l!&8&l] &7This command is not allowed during FreeCam mode.             &8&l[&c&l!&8&l] &7Type &5/freecam stop &7to cancel FreeCam mode."
##################################################
#                 Freecam Settings               #
##################################################
freecam-cooldown-seconds: 45
freecam-period: 30
freecam-max-distance: 120
freecam-whitelisted-commands:
  - /freecam stop
  - /roam stop
##################################################
#                   Economy                      #
##################################################
freecam-charge-money: false
freecam-cost: 1000

##################################################
#             LunarFreecam Perms                 #
##################################################
# freecam.use Allow players to use /freecam
# freecam.reload Allow Players to reload the plugin